Rework matchmaking algorithm for CL
brendanfly/wzclot pull request #103
Opened 2021-01-24 16:44 UTC by JustinReiter

PR makes a change so a different algorithm is used when creating matchups for CL. The new algorithm should prevent any deadlocks and mismatches leading to impossible matchups in later rounds. The algo will only apply to CL games, where the remainder of games will follow the standard process_new_games from RRTournaments.

2021-02-20 20:38 UTC, JustinR17 commented
Latest commits moves the update player clan function to a separate thread that runs once a day (instead of on the worker routine that runs hourly. Also fixed the sub command as before it was not finding the correct tournament players.

2021-02-27 19:19 UTC, JustinR17 commented on wlct/tournaments.py
> +        games = TournamentGame.objects.filter(tournament=self)
Changed this as I wasnt entirely sure why only unfinished games were checked. Should include all games to make sure all pairs are found

2021-03-02 01:20 UTC, brendanfly requested changes

2021-03-02 17:47 UTC, brendanfly approved these changes

2021-03-02 17:48 UTC, merged